<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:fase2="http://rep.oio.dk/skat.dk/intrastat/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" name="IndberetningRettighederHentService" targetNamespace="http://rep.oio.dk/skat.dk/intrastat/">
	<types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://rep.oio.dk/skat.dk/intrastat/">
			<xsd:include schemaLocation="http://85.81.229.78/rel_rep.oio.dk/skat.dk/intrastat/service/IndberetningRettighederHentInterface.xsd"/>
		</xsd:schema>
	</types>
	<message name="IndberetningRettighederHentServiceRequest">
		<part name="Request" element="fase2:IndberetningRettighederHent_I"/>
	</message>
	<message name="IndberetningRettighederHentServiceResponse">
		<part name="Response" element="fase2:IndberetningRettighederHent_O"/>
	</message>
	<portType name="IndberetningRettighederHentServicePortType">
		<operation name="getIndberetningRettighederHent">
			<input message="fase2:IndberetningRettighederHentServiceRequest"/>
			<output message="fase2:IndberetningRettighederHentServiceResponse"/>
		</operation>
	</portType>
	<binding name="IndberetningRettighederHentServiceBinding" type="fase2:IndberetningRettighederHentServicePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="getIndberetningRettighederHent">
			<soap:operation soapAction="getIndberetningRettighederHent"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="IndberetningRettighederHentServiceBindingQSService">
		<port name="IndberetningRettighederHentServiceBindingQSPort" binding="fase2:IndberetningRettighederHentServiceBinding">
			<soap:address location="http://85.81.229.78:8080/IndberetningRettighederHent"/>
		</port>
	</service>
	<xs:annotation xmlns:xs="http://www.w3.org/2001/XMLSchema">
		<xs:documentation>Dette er en simplificeret frontend for en eksisterende service og er oprettet mhp. en OIO-service.Kontroller om en revisor er registreret for en given angivelsetype for en given virksomhed. </xs:documentation>
	</xs:annotation>
</definitions>
