<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:intrastat="http://rep.oio.dk/skat.dk/intrastat/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" name="ListeAngivelseFilOpretService" targetNamespace="http://rep.oio.dk/skat.dk/intrastat/">
	<types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://rep.oio.dk/skat.dk/intrastat/">
			<xsd:include schemaLocation="http://rep.oio.dk/skat.dk/intrastat/service/ListeAngivelseFilOpretInterface.xsd"/>
		</xsd:schema>
	</types>
	<message name="ListeAngivelseFilOpretServiceRequest">
		<part name="Request" element="intrastat:ListeAngivelseFilOpret_I"/>
	</message>
	<message name="ListeAngivelseFilOpretServiceResponse">
		<part name="Response" element="intrastat:ListeAngivelseFilOpret_O"/>
	</message>
	<portType name="ListeAngivelseFilOpretServicePortType">
		<operation name="getListeAngivelseFilOpret">
			<input message="intrastat:ListeAngivelseFilOpretServiceRequest"/>
			<output message="intrastat:ListeAngivelseFilOpretServiceResponse"/>
		</operation>
	</portType>
	<binding name="ListeAngivelseFilOpretServiceBinding" type="intrastat:ListeAngivelseFilOpretServicePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="getListeAngivelseFilOpret">
			<soap:operation soapAction="getListeAngivelseFilOpret"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="ListeAngivelseFilOpretServiceBindingQSService">
		<port name="ListeAngivelseFilOpretServiceBindingQSPort" binding="intrastat:ListeAngivelseFilOpretServiceBinding">
			<soap:address location="http://85.81.229.78:8080/ListeAngivelseFilOpret"/>
		</port>
	</service>
</definitions>
