<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="urn:oio:skat:tfe:ws:1.0.1" name="OIOSummariskIndgangsangivelseSamlingOmdirigerService" xmlns:tfe="urn:oio:skat:tfe:ws:1.0.1" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
	<xs:annotation xmlns:xs="http://www.w3.org/2001/XMLSchema">
		<xs:documentation>Service</xs:documentation>
	</xs:annotation>
	<types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:oio:skat:tfe:ws:1.0.1">
			<xsd:include schemaLocation="http://digitaliser.dk/resource/540467/artefact/OIOSummariskIndgangsangivelseSamlingOmdirigerInterface.xsd"/>
		</xsd:schema>
	</types>
	<message name="OIOSummariskIndgangsangivelseSamlingOmdirigerServiceRequest">
		<part name="Request" element="tfe:OIOSummariskIndgangsangivelseSamlingOmdiriger_I"/>
	</message>
	<message name="OIOSummariskIndgangsangivelseSamlingOmdirigerServiceResponse">
		<part name="Response" element="tfe:OIOSummariskIndgangsangivelseSamlingOmdiriger_O"/>
	</message>
	<portType name="OIOSummariskIndgangsangivelseSamlingOmdirigerServicePortType">
		<operation name="getOIOSummariskIndgangsangivelseSamlingOmdiriger">
			<input message="tfe:OIOSummariskIndgangsangivelseSamlingOmdirigerServiceRequest"/>
			<output message="tfe:OIOSummariskIndgangsangivelseSamlingOmdirigerServiceResponse"/>
		</operation>
	</portType>
	<binding name="OIOSummariskIndgangsangivelseSamlingOmdirigerServiceBinding" type="tfe:OIOSummariskIndgangsangivelseSamlingOmdirigerServicePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="getOIOSummariskIndgangsangivelseSamlingOmdiriger">
			<soap:operation soapAction="getOIOSummariskIndgangsangivelseSamlingOmdiriger"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="OIOSummariskIndgangsangivelseSamlingOmdirigerServiceBindingQSService">
		<port name="OIOSummariskIndgangsangivelseSamlingOmdirigerServiceBindingQSPort" binding="tfe:OIOSummariskIndgangsangivelseSamlingOmdirigerServiceBinding">
			<soap:address location="http://sktdics04esb01.csc.dk:7013/SummariskIndgangsangivelseSamlingOmdiriger/SummariskIndgangsangivelseSamlingOmdirigerService" />
		</port>
	</service>
</definitions>
