
set authoritiesDIR=Til erhvervslivet\Wsdl-xsd Manifest Authorities (v24 - 15052012)
set transportDIR=Til erhvervslivet\Wsdl-xsd Manifest part 1 - Transport (v24 - 15052012)
set temporarystorageDIR=Til erhvervslivet\Wsdl-xsd Manifest part 2 - Temporary Storage  (v24 - 15052012)

rd /S /Q "Til erhvervslivet"
md "Til erhvervslivet"
md "%authoritiesDIR%"
md "%transportDIR%"
md "%temporarystorageDIR%"

robocopy . "%authoritiesDIR%" OIOEksternAnkomstOgAfgangsIndberetningOpret.wsdl OIOEksternAnkomstOgAfgangsIndberetningOpret_IType.xsd OIOEksternAnkomstOgAfgangsIndberetningOpret_OType.xsd OIOEksternAnkomstOgAfgangsIndberetningOpretInterface.xsd DKA16A.xsd DKA17A.xsd DKA18A.xsd DK917B.xsd simple_types.xsd simple_types_manifest.xsd complex_types_manifest.xsd doc.xsd tcl.xsd tcl_manifest.xsd SKAT_AdvisIdentifikator.xsd SKAT_AdvisStruktur.xsd SKAT_AdvisTekst.xsd SKAT_FejlIdentifikator.xsd SKAT_FejlStruktur.xsd SKAT_FejlTekst.xsd SKAT_HovedOplysninger.xsd SKAT_HovedOplysningerSvar.xsd SKAT_ServiceIdentifikator.xsd SKAT_SvarStruktur.xsd SKAT_TransaktionIdentifikator.xsd SKAT_TransaktionTid.xsd

robocopy . "%transportDIR%" complex_types_manifest.xsd DK917B.xsd DKA44A.xsd DKA47A.xsd DKA54A.xsd DKA60A.xsd DKA61A.xsd DKA62A.xsd DKA63A.xsd DKA64A.xsd DKA84A.xsd DKA87A.xsd DKA88A.xsd DKA89A.xsd DKA94A.xsd DKA95A.xsd DKA96A.xsd DKD44A.xsd DKD47A.xsd DKD48A.xsd DKD49A.xsd DKD51A.xsd DKD52A.xsd DKD53A.xsd DKD84A.xsd DKD87A.xsd DKD88A.xsd DKD89A.xsd DKD94A.xsd DKD95A.xsd DKD96A.xsd doc.xsd OIOAfgangsdeklarationOpdater.wsdl OIOAfgangsdeklarationOpdaterInterface.xsd OIOAfgangsdeklarationOpdater_IType.xsd OIOAfgangsdeklarationOpdater_OType.xsd OIOAfgangsdeklarationOpret.wsdl OIOAfgangsdeklarationOpretInterface.xsd OIOAfgangsdeklarationOpret_IType.xsd OIOAfgangsdeklarationOpret_OType.xsd OIOAfgangsdeklarationSlet.wsdl OIOAfgangsdeklarationSletInterface.xsd OIOAfgangsdeklarationSlet_IType.xsd OIOAfgangsdeklarationSlet_OType.xsd OIOAnkomstdeklarationOpdater.wsdl OIOAnkomstdeklarationOpdaterInterface.xsd OIOAnkomstdeklarationOpdater_IType.xsd OIOAnkomstdeklarationOpdater_OType.xsd OIOAnkomstdeklarationOpret.wsdl OIOAnkomstdeklarationOpretInterface.xsd OIOAnkomstdeklarationOpret_IType.xsd OIOAnkomstdeklarationOpret_OType.xsd OIOAnkomstdeklarationSlet.wsdl OIOAnkomstdeklarationSletInterface.xsd OIOAnkomstdeklarationSlet_IType.xsd OIOAnkomstdeklarationSlet_OType.xsd simple_types.xsd simple_types_manifest.xsd SKAT_AdvisIdentifikator.xsd SKAT_AdvisStruktur.xsd SKAT_AdvisTekst.xsd SKAT_FejlIdentifikator.xsd SKAT_FejlStruktur.xsd SKAT_FejlTekst.xsd SKAT_HovedOplysninger.xsd SKAT_HovedOplysningerSvar.xsd SKAT_ServiceIdentifikator.xsd SKAT_SvarStruktur.xsd SKAT_TransaktionIdentifikator.xsd SKAT_TransaktionTid.xsd tcl.xsd tcl_manifest.xsd

robocopy . "%temporarystorageDIR%" complex_types_manifest.xsd DK917B.xsd DKA01A.xsd DKA02A.xsd DKA03A.xsd DKA04A.xsd DKA05A.xsd DKA10A.xsd DKA11A.xsd DKA12A.xsd DKA13A.xsd DKA14A.xsd DKA15A.xsd DKA19A.xsd DKA20A.xsd DKA21A.xsd DKA52A.xsd DKA53A.xsd DKA55A.xsd DKA56A.xsd DKA57A.xsd DKA58A.xsd DKA59A.xsd DKA65A.xsd DKA66A.xsd DKA67A.xsd DKA69A.xsd DKA70A.xsd DKA71A.xsd DKA72A.xsd DKA73A.xsd DKA74A.xsd DKA75A.xsd DKA76A.xsd DKA77A.xsd DKA79A.xsd DKA80A.xsd DKA81A.xsd DKA82A.xsd DKA85A.xsd DKA86A.xsd DKA90A.xsd DKA97A.xsd DKA98A.xsd DKA99A.xsd doc.xsd OIOMidlertidigOpbevaringOpdater.wsdl OIOMidlertidigOpbevaringOpdaterInterface.xsd OIOMidlertidigOpbevaringOpdater_IType.xsd OIOMidlertidigOpbevaringOpdater_OType.xsd OIOMidlertidigOpbevaringOpret.wsdl OIOMidlertidigOpbevaringOpretInterface.xsd OIOMidlertidigOpbevaringOpret_IType.xsd OIOMidlertidigOpbevaringOpret_OType.xsd OIOMidlertidigOpbevaringOpsplitOpret.wsdl OIOMidlertidigOpbevaringOpsplitOpretInterface.xsd OIOMidlertidigOpbevaringOpsplitOpret_IType.xsd OIOMidlertidigOpbevaringOpsplitOpret_OType.xsd OIOMidlertidigOpbevaringSlet.wsdl OIOMidlertidigOpbevaringSletInterface.xsd OIOMidlertidigOpbevaringSlet_IType.xsd OIOMidlertidigOpbevaringSlet_OType.xsd OIOTolddokumentSamlingHent.wsdl OIOTolddokumentSamlingHentInterface.xsd OIOTolddokumentSamlingHent_IType.xsd OIOTolddokumentSamlingHent_OType.xsd simple_types.xsd simple_types_manifest.xsd SKAT_AdvisIdentifikator.xsd SKAT_AdvisStruktur.xsd SKAT_AdvisTekst.xsd SKAT_FejlIdentifikator.xsd SKAT_FejlStruktur.xsd SKAT_FejlTekst.xsd SKAT_HovedOplysninger.xsd SKAT_HovedOplysningerSvar.xsd SKAT_ServiceIdentifikator.xsd SKAT_SvarStruktur.xsd SKAT_TransaktionIdentifikator.xsd SKAT_TransaktionTid.xsd tcl.xsd tcl_manifest.xsd