<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:esws="urn:oio:skat:es:ws:1.0.0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="OIOAbonnentVirksomhedStamOplysningHentService" targetNamespace="urn:oio:skat:es:ws:1.0.0">
         <xs:annotation xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:documentation>Formålet er at hente stamoplysninger for en virksomhed. Der hentes oplysninger, som er gældende pr. dags dato.  Der hentes oplysninger om: Virksomhedens start- og eventuelle ophørsdato i relation til told-, skatte- og afgiftslovgivningen, virksomhedens korte og lange navn, virksomhedens adresse samt eventuel tele-fonnummer og EmailAdresse.  Servicen udstilles alene til de myndigheder og andre, som har indgået en abonnementsaftale med told- og Skatteforvaltningen herom. </xs:documentation>
            <xs:documentation>1.0</xs:documentation>
            <xs:documentation>r26495</xs:documentation>
         </xs:annotation>
         <wsdl:types>
            <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:oio:skat:es:ws:1.0.0">
               <xsd:include schemaLocation="urn/oio/skat/es/ws/1_0_0/OIOAbonnentVirksomhedStamOplysningHentInterface.xsd"/>
            </xsd:schema>
         </wsdl:types>
         <wsdl:message name="OIOAbonnentVirksomhedStamOplysningHentServiceRequest">
            <wsdl:part element="esws:OIOAbonnentVirksomhedStamOplysningHent_I" name="Request"/>
         </wsdl:message>
         <wsdl:message name="OIOAbonnentVirksomhedStamOplysningHentServiceResponse">
            <wsdl:part element="esws:OIOAbonnentVirksomhedStamOplysningHent_O" name="Response"/>
         </wsdl:message>
         <wsdl:portType name="OIOAbonnentVirksomhedStamOplysningHentServicePortType">
            <wsdl:operation name="getOIOAbonnentVirksomhedStamOplysningHent">
               <wsdl:input message="esws:OIOAbonnentVirksomhedStamOplysningHentServiceRequest"/>
               <wsdl:output message="esws:OIOAbonnentVirksomhedStamOplysningHentServiceResponse"/>
            </wsdl:operation>
         </wsdl:portType>
         <wsdl:binding name="OIOAbonnentVirksomhedStamOplysningHentServiceBinding" type="esws:OIOAbonnentVirksomhedStamOplysningHentServicePortType" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
<wsdl:operation name="getOIOAbonnentVirksomhedStamOplysningHent">
<soap:operation soapAction="getOIOAbonnentVirksomhedStamOplysningHent" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
<wsdl:input>
<soap:body use="literal" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
</wsdl:input>
<wsdl:output>
<soap:body use="literal" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="OIOAbonnentVirksomhedStamOplysningHentServiceBindingQSService">
		<wsdl:port name="OIOAbonnentVirksomhedStamOplysningHentServiceBindingQSPort" binding="esws:OIOAbonnentVirksomhedStamOplysningHentServiceBinding">
			<soap:address location="https://services.extranet.skat.dk/vericert/services/OIOAbonnentVirksomhedStamOplysningHentServicePort"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
