<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:struct="urn:oio:skat:emcs:ws:1.0.1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:oio:skat:emcs:ws:1.0.1" name="OIOForsendelseAfbrydelseBeskedSamlingHentService">
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:oio:skat:emcs:ws:1.0.1">
			<xsd:include schemaLocation="../service/OIOForsendelseAfbrydelseBeskedSamlingHentInterface.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="OIOForsendelseAfbrydelseBeskedSamlingHentServiceRequest">
		<wsdl:part name="Request" element="struct:OIOForsendelseAfbrydelseBeskedSamlingHent_I"/>
	</wsdl:message>
	<wsdl:message name="OIOForsendelseAfbrydelseBeskedSamlingHentServiceResponse">
		<wsdl:part name="Response" element="struct:OIOForsendelseAfbrydelseBeskedSamlingHent_O"/>
	</wsdl:message>
	<wsdl:portType name="OIOForsendelseAfbrydelseBeskedSamlingHentServicePortType">
		<wsdl:operation name="getOIOForsendelseAfbrydelseBeskedSamlingHent">
			<wsdl:input message="struct:OIOForsendelseAfbrydelseBeskedSamlingHentServiceRequest"/>
			<wsdl:output message="struct:OIOForsendelseAfbrydelseBeskedSamlingHentServiceResponse"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>
