<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:struct="urn:oio:skat:emcs:ws:1.0.1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:oio:skat:emcs:ws:1.0.1" name="OIOLedsageDokumentNotifikationSamlingHentService">
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:oio:skat:emcs:ws:1.0.1">
			<xsd:include schemaLocation="../service/OIOLedsageDokumentNotifikationSamlingHentInterface.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="OIOLedsageDokumentNotifikationSamlingHentServiceRequest">
		<wsdl:part name="Request" element="struct:OIOLedsageDokumentNotifikationSamlingHent_I"/>
	</wsdl:message>
	<wsdl:message name="OIOLedsageDokumentNotifikationSamlingHentServiceResponse">
		<wsdl:part name="Response" element="struct:OIOLedsageDokumentNotifikationSamlingHent_O"/>
	</wsdl:message>
	<wsdl:portType name="OIOLedsageDokumentNotifikationSamlingHentServicePortType">
		<wsdl:operation name="getOIOLedsageDokumentNotifikationSamlingHent">
			<wsdl:input message="struct:OIOLedsageDokumentNotifikationSamlingHentServiceRequest"/>
			<wsdl:output message="struct:OIOLedsageDokumentNotifikationSamlingHentServiceResponse"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>
