<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:spilws="urn:oio:skat:spil:ws:1.0.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:oio:skat:spil:ws:1.0.0" name="ModtagSpilleAfgiftGebyrAngivelseService">
	<xs:annotation xmlns:xs="http://www.w3.org/2001/XMLSchema">
		<xs:documentation>Formålet med denne service er, at virksomheden vha. menuen Punktafgifter stoerre end Filoverfør (SPIL) med en xml-fil skal kunne indberette antallet af spilleautomater for angivelse af det faste gebyr for hver enkelt opstillet spilleautomat samt de månedlige angivelser med tilhørende specifikationer og evt. Supplerende oplysninger (udlodninger til velgørende formål).</xs:documentation>
	</xs:annotation>
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:oio:skat:spil:ws:1.0.0">
			<xsd:include schemaLocation="urn/oio/skat/spil/ws/1_0_0/ModtagSpilleAfgiftGebyrAngivelseInterface.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="ModtagSpilleAfgiftGebyrAngivelseServiceRequest">
		<wsdl:part name="Request" element="spilws:ModtagSpilleAfgiftGebyrAngivelse_I"/>
	</wsdl:message>
	<wsdl:message name="ModtagSpilleAfgiftGebyrAngivelseServiceResponse">
		<wsdl:part name="Response" element="spilws:ModtagSpilleAfgiftGebyrAngivelse_O"/>
	</wsdl:message>
	<wsdl:portType name="ModtagSpilleAfgiftGebyrAngivelseServicePortType">
		<wsdl:operation name="getModtagSpilleAfgiftGebyrAngivelse">
			<wsdl:input message="spilws:ModtagSpilleAfgiftGebyrAngivelseServiceRequest"/>
			<wsdl:output message="spilws:ModtagSpilleAfgiftGebyrAngivelseServiceResponse"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>
