<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://rep.oio.dk/skat.dk/eindkomst/" name="IndkomstOplysningPersonAbonnementAjourførService" xmlns:fase2="http://rep.oio.dk/skat.dk/eindkomst/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
	<xs:annotation xmlns:xs="http://www.w3.org/2001/XMLSchema">
		<xs:documentation>Formålet er at vedligeholde et abonnement på fremtidige ændringer i indkomstoplysninger for en kreds af personer. Anvendelsen af servicen er betinget af, at de pågældende har indgået en abonnementsaftale med told- og skatteforvaltningen herom, jf. § 7 stk. 4 i lov om et indkomstregister. Servicen udstilles ikke til enhver og må således alene anvendes af kendte brugere, dvs. af de myndighe-der m.fl., som abonnerer på indkomstoplysninger. eIndkomstPersonIndkomstAbonnementGyldigFra angiver den dato, som abonnementet gælder fra og med. eIndkomstPersonIndkomstAbonnementGyldigTil angiver den dato, som abonnementet ophører fra og med. En af datoerne skal angives. Start- og slutdato kan ikke være før eller efter dags dato. Det er ikke muligt at ændre en allerede ajourført start- eller slutdato for abonnement. Der må oprettes nyt abonnement. Som tekst for abonnentadgangomgang angives navnet på den service, som stiller indkomstoplysningerne til rådighed. </xs:documentation>
	</xs:annotation>
	<wsdl:types>
		<xsd:schema targetNamespace="http://rep.oio.dk/skat.dk/eindkomst/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:include schemaLocation="../service/IndkomstOplysningPersonAbonnementAjourfoerInterface.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="IndkomstOplysningPersonAbonnementAjourførServiceRequest">
		<wsdl:part name="Request" element="fase2:IndkomstOplysningPersonAbonnementAjourfør_I"/>
	</wsdl:message>
	<wsdl:message name="IndkomstOplysningPersonAbonnementAjourførServiceResponse">
		<wsdl:part name="Response" element="fase2:IndkomstOplysningPersonAbonnementAjourfør_O"/>
	</wsdl:message>
	<wsdl:portType name="IndkomstOplysningPersonAbonnementAjourførServicePortType">
		<wsdl:operation name="getIndkomstOplysningPersonAbonnementAjourfør">
			<wsdl:input message="fase2:IndkomstOplysningPersonAbonnementAjourførServiceRequest"/>
			<wsdl:output message="fase2:IndkomstOplysningPersonAbonnementAjourførServiceResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="IndkomstOplysningPersonAbonnementAjourførServiceBinding" type="fase2:IndkomstOplysningPersonAbonnementAjourførServicePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="getIndkomstOplysningPersonAbonnementAjourfør">
			<soap:operation soapAction="getIndkomstOplysningPersonAbonnementAjourfør"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="IndkomstOplysningPersonAbonnementAjourførServiceBindingQSService">
		<wsdl:port name="IndkomstOplysningPersonAbonnementAjourførServiceBindingQSPort" binding="fase2:IndkomstOplysningPersonAbonnementAjourførServiceBinding">
			<soap:address location="https://services.extranet.skat.dk/vericert/services/IndkomstOplysningPersonAbonnementAjourfoerServicePort"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
