<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://rep.oio.dk/skat.dk/eindkomst/" name="AsynkronCallback" xmlns:fase2="http://rep.oio.dk/skat.dk/eindkomst/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://www.w3.org/2001/XMLSchema">
	<xs:annotation xmlns:xs="http://www.w3.org/2001/XMLSchema">
		<xs:documentation>
		Formålet er at give en abonnent besked om at bestilling af data er udført og klar til afhentning. Input er et bestillings-id.
		</xs:documentation>
	</xs:annotation>
	<types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://rep.oio.dk/skat.dk/eindkomst/">
			<xsd:include schemaLocation="../service/AsynkronCallbackInterface.xsd"/>
		</xsd:schema>
	</types>
	
	<message name="AsynkronCallbackServiceRequest">
		<part name="Request" element="fase2:AsynkronCallback_I"/>
	</message>
	<message name="AsynkronCallbackServiceResponse">
		<part name="Response" element="fase2:AsynkronCallback_O"/>
	</message>
	
	<portType name="AsynkronCallbackServicePortType">
		<operation name="getAsynkronCallback">
			<input message="fase2:AsynkronCallbackServiceRequest"/>
			<output message="fase2:AsynkronCallbackServiceResponse"/>
		</operation>
	</portType>

</definitions>
