<?xml version="1.0" encoding="UTF-8"?>
      <xs:schema xmlns:skat2012="http://skat.dk/begrebsmodel/2012/01/01/"
                 xmlns:xs="http://www.w3.org/2001/XMLSchema"
                 targetNamespace="http://skat.dk/begrebsmodel/2012/01/01/"
                 elementFormDefault="qualified"
                 version="1.0">
         <xs:include schemaLocation="../types/Tekst32Type.xsd"/>
         
         <xs:element name="EUMeddeleIseSystem" type="skat2012:Tekst32Type">
            <xs:annotation>
               <xs:documentation>Transient dataelement, som angiver hvilket system der skal udveksle EU-meddelelsen. Her anvendes EUs navngivning, fx EMCS, VATRefund (Momsrefusion), mv.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:schema>
