<?xml version="1.0" encoding="UTF-8"?>
      <xs:schema xmlns:skat2012="http://skat.dk/begrebsmodel/2012/01/01/"
                 xmlns:xs="http://www.w3.org/2001/XMLSchema"
                 targetNamespace="http://skat.dk/begrebsmodel/2012/01/01/"
                 elementFormDefault="qualified"
                 version="1.0">
         <xs:include schemaLocation="../types/EUMeddelelseKomprimeretAlgoritmeType.xsd"/>
         
         <xs:element name="EUMeddelelseKomprimeretAlgoritme"
                     type="skat2012:EUMeddelelseKomprimeretAlgoritmeType">
            <xs:annotation>
               <xs:documentation>Transient dataelement, som angiver typen af komprimeringsalgoritme, hvis EU-meddelelsen er komprimeret.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:schema>
