<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:efiws="urn:oio:skat:efi:ws:1.0.1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:oio:skat:efi:ws:1.0.1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
	xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702" xmlns:wsp="http://www.w3.org/ns/ws-policy"	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"   
	name="MFKvitteringHentService">

	<xs:include schemaLocation="policy/skat-b2b-x509-policy.xml" />

	<xs:annotation xmlns:xs="http://www.w3.org/2001/XMLSchema">
		<xs:documentation>Hent resultater (kvitteringer) fra den asynkrone behandling af fordringsaktioner indberettet med MFFordringIndberet.</xs:documentation>
	</xs:annotation>
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:oio:skat:efi:ws:1.0.1">
			<xsd:include schemaLocation="urn/oio/skat/efi/ws/1_0_1/MFKvitteringHentInterface.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="MFKvitteringHentServiceRequest">
		<wsdl:part name="Request" element="efiws:MFKvitteringHent_I"/>
	</wsdl:message>
	<wsdl:message name="MFKvitteringHentServiceResponse">
		<wsdl:part name="Response" element="efiws:MFKvitteringHent_O"/>
	</wsdl:message>
	<wsdl:portType name="MFKvitteringHentServicePortType">
		<wsdl:operation name="getMFKvitteringHent">
			<wsdl:input message="efiws:MFKvitteringHentServiceRequest"/>
			<wsdl:output message="efiws:MFKvitteringHentServiceResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="MFKvitteringHentServiceBinding" type="efiws:MFKvitteringHentServicePortType">
		<wsp:PolicyReference URI="policy/skat-b2b-x509-policy.xml#skat-b2b-x509-policy"/>
		<soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="getMFKvitteringHent">
			<soap12:operation soapAction="getMFKvitteringHent"/>
			<wsdl:input>
				<soap12:body use="literal"/>
				<wsp:PolicyReference URI="policy/skat-b2b-x509-policy.xml#skat-b2b-x509-policy"/>
			</wsdl:input>
			<wsdl:output>
				<soap12:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="MFKvitteringHentServiceBindingQSService">
		<wsdl:port name="MFKvitteringHentHentServiceBindingQSPort" binding="efiws:MFKvitteringHentServiceBinding">
			<soap12:address location="https://some.url.here"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
