<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:selvangivelsews="urn:oio:skat:selvangivelse:ws:1.0.0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="PersonSelvangivelseOpretService" targetNamespace="urn:oio:skat:selvangivelse:ws:1.0.0">
         <xs:annotation xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:documentation>At indberette oplysningsskemaet (S10) og returnere den opdaterede årsopgørelse inkl. evt. ægtefælles.</xs:documentation>
            <xs:documentation>3.15</xs:documentation>
            <xs:documentation>r24807</xs:documentation>
         </xs:annotation>
         <wsdl:types>
            <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:oio:skat:selvangivelse:ws:1.0.0">
               <xsd:include schemaLocation="urn/oio/skat/selvangivelse/ws/1_0_0/PersonSelvangivelseOpretInterface.xsd"/>
            </xsd:schema>
         </wsdl:types>
         <wsdl:message name="PersonSelvangivelseOpretServiceRequest">
            <wsdl:part element="selvangivelsews:PersonSelvangivelseOpret_I" name="Request"/>
         </wsdl:message>
         <wsdl:message name="PersonSelvangivelseOpretServiceResponse">
            <wsdl:part element="selvangivelsews:PersonSelvangivelseOpret_O" name="Response"/>
         </wsdl:message>
         <wsdl:portType name="PersonSelvangivelseOpretServicePortType">
            <wsdl:operation name="getPersonSelvangivelseOpret">
               <wsdl:input message="selvangivelsews:PersonSelvangivelseOpretServiceRequest"/>
               <wsdl:output message="selvangivelsews:PersonSelvangivelseOpretServiceResponse"/>
            </wsdl:operation>
         </wsdl:portType>
         <wsdl:binding name="PersonSelvangivelseOpretServiceBinding" type="selvangivelsews:PersonSelvangivelseOpretServicePortType" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
<wsdl:operation name="getPersonSelvangivelseOpret">
<soap:operation soapAction="getPersonSelvangivelseOpret" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
<wsdl:input>
<soap:body use="literal" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
</wsdl:input>
<wsdl:output>
<soap:body use="literal" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="PersonSelvangivelseOpretServiceBindingQSService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
<wsdl:port binding="selvangivelsews:PersonSelvangivelseOpretServiceBinding" name="PersonSelvangivelseOpretServiceBindingQSPort">
<soap:address location="https://xxxxxxxxx/PersonSelvangivelseOpretServicePort" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>
