<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:dmr="http://skat.dk/dmr/2007/05/31/" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://skat.dk/dmr/2007/05/31/" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<xs:annotation>
		<xs:documentation>Da mængden af udstyr for det enkelte køretøj kan være enorm og under løbende forbedringer, er der opbygget muligheden for løbende at definere specialudstyr, som ikke direkte er primærattributter på køretøjet. Udstyrstyperne kan være opbygget i et hierarki. Derudover er udstyret grupperet i udstyrsgrupper.  Udstyr, der altid skal vises er markeret med (x). Udstyr, der ikke er markeret med (x) skal kun vises i forbindelse med syn. Udstyr, der er markeret med (mc) skal kun vises i forbindelse med syn af en motorcykel. ABS skal altid vises ved oprettelse.  Følgende udstyr skal defineres i DMR: (Udstyrsgrupper er skrevet med store bogstaver)  100 - ANDET  110 - UDSTYR  405 - højrestyring 506 - ABS bremser (mc) (X) 713 - tunet motor 717 - ESP (Elektronisk Stabiliserings Program) 999 - integreret barnesæde 6028 - selealarm (X) 6029 - radio (X) 9019 - u. siderude i v. side af varerum 9901 - airbags (X) </xs:documentation>
	</xs:annotation>
	<xs:include schemaLocation="../types/TalHelType.xsd"/>
	<xs:include schemaLocation="../types/TekstKortType.xsd"/>
	<xs:include schemaLocation="../types/BolskType.xsd"/>
	<xs:element name="KoeretoejUdstyrTypeNummer" type="dmr:TalHelType">
		<xs:annotation>
			<xs:documentation>UdstyrType nummer</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="KoeretoejUdstyrTypeNavn" type="dmr:TekstKortType">
		<xs:annotation>
			<xs:documentation>UdstyrType navn.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="KoeretoejUdstyrTypeStandardAntal" type="dmr:TalHelType">
		<xs:annotation>
			<xs:documentation>Angiver en antalsværdi, som automatisk foreslås i antal-feltet, når dette stykke udstyr tilknyttes.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="KoeretoejUdstyrTypeVisesVedSyn" type="dmr:BolskType">
		<xs:annotation>
			<xs:documentation>Er denne attribut sand skal instansen kun vises ved syn.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="KoeretoejUdstyrTypeVisesVedForespoergsel" type="dmr:BolskType">
		<xs:annotation>
			<xs:documentation>Er denne attribut sand skal instansen kun vises ved køretøjoprettelse ud fra forespørgelse .</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="KoeretoejUdstyrTypeVisesVedStandardOprettelse" type="dmr:BolskType">
		<xs:annotation>
			<xs:documentation>Er denne attribut sand skal instansen kun vises ved køretøjoprettelse ud fra standard oprettelse.</xs:documentation>
		</xs:annotation>
	</xs:element>
</xs:schema>
