<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:eindkomstws="urn:oio:skat:eindkomst:ws:1.0.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="urn:oio:skat:eindkomst:ws:1.0.0" name="OekonomiskYdelseBerettigetProcentHentService">
	<xs:annotation xmlns:xs="http://www.w3.org/2001/XMLSchema">
		<xs:documentation>Formålet er at udstille oplysninger om den berettiget procentsats (og beregningsgrundlag) i forbindelse med udbetaling af økonomiske ydelser til en given person. Det gælder fx for Børn og Unge Ydelse (BUY).</xs:documentation>
	</xs:annotation>
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:oio:skat:eindkomst:ws:1.0.0">
			<xsd:include schemaLocation="../service/OEkonomiskYdelseBerettigetProcentHentInterface.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="OekonomiskYdelseBerettigetProcentHentServiceRequest">
		<wsdl:part name="Request" element="eindkomstws:OekonomiskYdelseBerettigetProcentHent_I"/>
	</wsdl:message>
	<wsdl:message name="OekonomiskYdelseBerettigetProcentHentServiceResponse">
		<wsdl:part name="Response" element="eindkomstws:OekonomiskYdelseBerettigetProcentHent_O"/>
	</wsdl:message>
	<wsdl:portType name="OekonomiskYdelseBerettigetProcentHentServicePortType">
		<wsdl:operation name="getOekonomiskYdelseBerettigetProcentHent">
			<wsdl:input message="eindkomstws:OekonomiskYdelseBerettigetProcentHentServiceRequest"/>
			<wsdl:output message="eindkomstws:OekonomiskYdelseBerettigetProcentHentServiceResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="OekonomiskYdelseBerettigetProcentHentServiceBinding" type="eindkomstws:OekonomiskYdelseBerettigetProcentHentServicePortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="getOekonomiskYdelseBerettigetProcentHent">
			<soap:operation soapAction="getOekonomiskYdelseBerettigetProcentHent"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="OekonomiskYdelseBerettigetProcentHentServiceBindingQSService">
		<wsdl:port name="OekonomiskYdelseBerettigetProcentHentServiceBindingQSPort" binding="eindkomstws:OekonomiskYdelseBerettigetProcentHentServiceBinding">
			<soap:address location="https://services.extranet.skat.dk/vericert/services/OekonomiskYdelseBerettigetProcentHentServicePort"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
