<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:efiws="urn:oio:skat:efi:ws:1.0.1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:oio:skat:efi:ws:1.0.1" name="MFUnderretSamlingHentService">
	<xs:annotation xmlns:xs="http://www.w3.org/2001/XMLSchema">
		<xs:documentation>At hente underretnings-meddelelser der ligger klar til fordringshaveren.</xs:documentation>
	</xs:annotation>
	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:oio:skat:efi:ws:1.0.1">
			<xsd:include schemaLocation="../service/MFUnderretSamlingHentInterface.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="MFUnderretSamlingHentServiceRequest">
		<wsdl:part name="Request" element="efiws:MFUnderretSamlingHent_I"/>
	</wsdl:message>
	<wsdl:message name="MFUnderretSamlingHentServiceResponse">
		<wsdl:part name="Response" element="efiws:MFUnderretSamlingHent_O"/>
	</wsdl:message>
	<wsdl:portType name="MFUnderretSamlingHentServicePortType">
		<wsdl:operation name="getMFUnderretSamlingHent">
			<wsdl:input message="efiws:MFUnderretSamlingHentServiceRequest"/>
			<wsdl:output message="efiws:MFUnderretSamlingHentServiceResponse"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>
